version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: musicapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "7777:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    volumes:
      - .:/server  # Mount the local app directory to enable hot reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:admin123@db:5432/musicapp
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /server

volumes:
  pg_data: